# .travis.yml

# Do not set the language to c++, this over rides our environment variable CXX
# below.
language: C

sudo: false

git:
    depth: 1

addons:
  apt:
    sources:
       - ubuntu-toolchain-r-test
    packages:
       - g++-5

os:
  - linux

env:
  - CXX="ccache g++-5"

# OMR compiles with g++, so ccache works for it
cache:
  ccache: true
  directories:
    - node_modules

install:
    - npm install

script:
    - mkdir build && cd build
    - cmake ..
    - make -j8
    - ctest --output-on-failure
