# Site Settings
title: Base9
email: arianne.leah@gmail.com
description: >
  An educational virtual machine
baseurl: ""
url: "http://localhost:4000"
github_username:  arianneb
theme: minima
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
